### ISSUE TITLE
Add kubectl-graph plugin to krew

### ISSUE THREAD

**Issue by ishantanu** [kubernetes-sigs/krew-index#503]
Hi,

As discussed in [awesome-kubectl-plugins sync issue](https://github.com/ishantanu/awesome-kubectl-plugins/issues/4), opening an issue to add [kubectl-graph](https://github.com/steveteuber/kubectl-graph) to krew index.

See the reference [awesome-kubectl-plugin repository's commit](https://github.com/ishantanu/awesome-kubectl-plugins/commit/0a937e58bff789b22d7e15bdb75f343c34fb0189) which added this plugin to the list.

**Comment by corneliusweig** [comment]
Hey @ishantanu, thanks for bringing this up. I think it's great that you just opened this issue and didn't create a PR. This is exactly how it should work :+1:

@steveteuber what is your opinion about bringing `kubectl-graph` into krew? It doesn't take much, you just have to write a manifest and update that with your most recent version if you do a release. Would you be open to maintain this?

---

I haven't tried the plugin so I don't know for sure what it does. It seems to be a good idea, to print a dependency graph though. My major problem right now is that it is hardly documented. Some documentation and maybe also an example on the project landing page would be great. Otherwise, users won't even know what this is all about.

Regarding the plugin name: I suspect that `graph` is too generic. Can you come up with a more specific name? Also, it would be nice to know how it relates to `kubectl tree` which is already in krew-index.

**Comment by steveteuber** [comment]
Hi @corneliusweig,

I've created the repository exactly one week ago. And yes, I would like to make this plugin available via `krew`. But first I need to create a fully working `kubectl` plugin. When everything works as expected, then I create a first release which can be added to the krew-index.

Regarding the plugin name, the generic name is intended to be universal. 
The task of the plugin is to get a dependency **graph** in different output formats, which can be used to visualize Kubernetes resources and relationships in _Graphviz_ or _Neo4j_.

Could you please assign this issue to me?

**Comment by corneliusweig** [comment]
@steveteuber 

> And yes, I would like to make this plugin available via `krew`

That's great. Looking forward to your submission!


> Regarding the plugin name, the generic name is intended to be universal.

I see. For krew we strive to avoid generic names though. It is much easier for users to discover your plugin if the name is more descriptive. Let's discuss this when you submit your plugin. However be prepared that there's a high chance we will not accept the generic name. As far as I understand, `resource-graph` would be a better choice. WDYT?

**Comment by ahmetb** [comment]
I am actually ok with “graph” name. You probably only can do a graph of “resource”s anyway so it’s sort of redundant. Similarly, “tree” could be “resource-tree” but to a good degree the implicit meaning can be easily understood.

**Comment by ahmetb** [comment]
@steveteuber let us know when you make progress and you can integrate with release automation we have https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/ to update this repo when you have a new version.
/hold

**Comment by ahmetb** [comment]
@steveteuber pinging for interest. happy to accept this as a plugin.

**Comment by steveteuber** [comment]
@ishantanu this issue can be closed. The plugin is now listed in the `krew-index`:

```
$ kubectl krew update
Updated the local copy of plugin index.
  New plugins available:
    * graph
```
