### ISSUE TITLE
Remove 'debug' plugin as builtin command graduates to beta in kubectl 1.20.0

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew-index#949]
`debug` is now a beta command in kubectl 1.20.0 giving the plugin in krew no option to be invoked from this point forward. We should probably delete it soon.

/cc @verb

**Comment by verb** [comment]
@ahmet I was going to ask your advice on this. I'd like to retire this plugin, but a handful of users I've talked to are "stuck" on old versions of kubectl (e.g. because they rely on kubectl bundled with gcloud or the like).

It seems like the "two version rule" might be a good rule of thumb, but the 'debug' plugin only ever supported adding ephemeral containers, which is an alpha feature, albeit one that existed 2 versions ago.

What do you think?

**Comment by ahmetb** [comment]
Agreed. It’s reasonable.

**Comment by corneliusweig** [comment]
Let's add a notice / caveat in the manifest that the `debug` plugin will not work for kubectl >=1.20. Then it should be fine to keep it for some time.
